[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --benchmark-columns=mean,min,max,stddev --benchmark-sort=name

[benchmark]
min_rounds = 5
max_time = 30.0
warmup = True
warmup_iterations = 2
disable_gc = True
columns = min,max,mean
autosave = True
sort = name
